name: unintently
description: "Unintently v2 - Free, Open-Source AI-Powered Text-to-Handwriting & Assignment Generator."
publish_to: 'none'

version: 2.2.0+3

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  pdf: ^3.13.1
  printing: ^5.15.1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  http: ^1.2.2
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  mobile_scanner: ^7.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/branding/
    - assets/fonts/

  fonts:
    - family: Writing1
      fonts:
        - asset: assets/fonts/Writing1.ttf
    - family: Writing2
      fonts:
        - asset: assets/fonts/Writing2.ttf
    - family: Writing3
      fonts:
        - asset: assets/fonts/Writing3.ttf
    - family: Writing4
      fonts:
        - asset: assets/fonts/Writing4.ttf
    - family: Writing5
      fonts:
        - asset: assets/fonts/Writing5.ttf
    - family: Writing7
      fonts:
        - asset: assets/fonts/Writing7.ttf
    - family: Writing8
      fonts:
        - asset: assets/fonts/Writing8.ttf
    - family: intentlyR1
      fonts:
        - asset: assets/fonts/intentlyR1.ttf
    - family: intentlyR2
      fonts:
        - asset: assets/fonts/intentlyR2.ttf
    - family: intentlyR8
      fonts:
        - asset: assets/fonts/intentlyR8.ttf
    - family: intentlyR11
      fonts:
        - asset: assets/fonts/intentlyR11.ttf
    - family: intentlyR12
      fonts:
        - asset: assets/fonts/intentlyR12.ttf
